// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTHJqHqVPNG172m-qeOcOzr3yF9DT7VSg',
    appId: '1:566821257691:web:9b5f78c6060e80da6767fe',
    messagingSenderId: '566821257691',
    projectId: 'spentwise-74be2',
    authDomain: 'spentwise-74be2.firebaseapp.com',
    storageBucket: 'spentwise-74be2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3_gOjfQj9vPdoRz276R8esxce4ipzYvs',
    appId: '1:566821257691:android:bee3458be02aae026767fe',
    messagingSenderId: '566821257691',
    projectId: 'spentwise-74be2',
    storageBucket: 'spentwise-74be2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArAGDN3wTPJQWRAPbWAWIdgJsSTQdeiik',
    appId: '1:566821257691:ios:478bc17f27f928e56767fe',
    messagingSenderId: '566821257691',
    projectId: 'spentwise-74be2',
    storageBucket: 'spentwise-74be2.appspot.com',
    iosBundleId: 'com.example.spentwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArAGDN3wTPJQWRAPbWAWIdgJsSTQdeiik',
    appId: '1:566821257691:ios:2ba23828070cc15f6767fe',
    messagingSenderId: '566821257691',
    projectId: 'spentwise-74be2',
    storageBucket: 'spentwise-74be2.appspot.com',
    iosBundleId: 'com.example.spentwise.RunnerTests',
  );
}
